Fixed the code to provision the RAID for MaaS physical
CloudBoltSoftware/cloudbolt-forge pull request #133
Opened 2022-01-18 04:09 UTC by yogeshmhaskule93

# Development Prerequisites
- **Developer:** @yogeshmhaskule93 
- **Partner:** None
- **Jira Story:** [DEV-19397](https://cloudbolt.atlassian.net/browse/DEV-19397)
- **Design Doc:** None

## Summary of Proposed Changes
* ...

2022-01-20 01:23 UTC, smallsam requested changes
Please move this to a technology specific folder like:
actions/cloudbolt_plugins/maas/configure_raid/maas_configure_raid.py

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +    is_physical = kwargs.get('physical', False)
```suggestion
    is_physical = not server.maas_machine_type
```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        set_progress("The MaaS plugine will fix up your MAAS machine {}, Cloudbolt Server id = {}; please stand by.".format(maas_id, server_id))
```suggestion
        set_progress("Configuring RAID on MAAS machine {}".format(maas_id))
```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +
```suggestion
    else:
        return "FAILURE", "", "Invalid (None) wrapper passed to plugin"

```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +
```suggestion

```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +    set_progress("Provisioning a physical MAAS machine.")
```suggestion

```
We're not provisioning the machine here.

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        rel = wrapper.maas_api_request("POST", "machines/{}/?op=release".format(maas_id), data = {"comment" : "making in ready state" })
Is this necessary? If we release then we risk it being consumed by another provision. 
It should be in allocated status at this point. Can we not re-configure raid in this state?

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        set_progress("Deleting RAID fields: {}".format(raid['name']))
```suggestion
        set_progress("Deleting RAID volume: {}".format(raid['name']))
```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        set_progress("Creating a RAID array for the machine.")
```suggestion
        set_progress("Creating a RAID-1 array md0 for the machine using all unused disks: {}".format(','.join([disk['name'] for disk in disks]))
```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        rel = wrapper.maas_api_request("POST", "machines/{}/?op=release".format(maas_id), data = {"comment" : "making in ready state" })
```suggestion

```
As per before, why are we releasing it again?

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        set_progress("Filesystem Format: block_device_id={}, fstype={}".format(block_device_id, fstype))
```suggestion
        set_progress("Formatting filesystem: block_device_id={}, fstype={}".format(block_device_id, fstype))
```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        set_progress("Filesystem mount: block_device_id={}, mount_point={}".format(block_device_id, mount_point))
```suggestion
        set_progress("Configuring mount point: block_device_id={}, mount_point={}".format(block_device_id, mount_point))
```

2022-01-20 01:23 UTC, smallsam commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        return "SUCCESS", "The MaaS during-provisioning plugin has completed.", ""
```suggestion
        return "SUCCESS", "Finished configuring RAID for MaaS machine", ""
```

2022-01-20 05:33 UTC, yogeshmhaskule93 commented on actions/orchestration/Provision_RAID_Physical_Server.py
> +        rel = wrapper.maas_api_request("POST", "machines/{}/?op=release".format(maas_id), data = {"comment" : "making in ready state" })
okey, will skip the further process, add logger message and exit with success.

2022-01-31 02:17 UTC, smallsam commented
> Please move this to a technology specific folder like: actions/cloudbolt_plugins/maas/configure_raid/maas_configure_raid.py

Please action this one.

2022-01-31 04:24 UTC, yogeshmhaskule93 commented
Yes, I did technology specific folder as mentioned above, its changed in second commit.

2022-02-03 07:53 UTC, smallsam requested changes

2022-02-03 07:53 UTC, smallsam commented on actions/cloudbolt_plugins/maas/configure_raid/maas_configure_raid.py
> +
Please  wrapper.client.allocate() to allocate the machine once you've finished configuring raid to return it to allocated state (since we only switch it back to ready as a workaround for the bug).

2022-02-03 07:53 UTC, smallsam commented on actions/cloudbolt_plugins/maas/configure_raid/maas_configure_raid.py
> +        # We need to move to machine in ready state to delete the existig raid, you can't delete raid if machine in allocated state
Please note this bug: https://bugs.launchpad.net/maas/+bug/1959169 is the reason for this behaviour

2022-02-03 07:59 UTC, yogeshmhaskule93 commented on actions/cloudbolt_plugins/maas/configure_raid/maas_configure_raid.py
> +        # We need to move to machine in ready state to delete the existig raid, you can't delete raid if machine in allocated state
Yes, It's correct I tried to delete existing raid with the help of "DELETE" api but it gives 409 error. So you need to make machine ready first and the do the delete operation on that.

2022-02-03 08:00 UTC, yogeshmhaskule93 commented on actions/cloudbolt_plugins/maas/configure_raid/maas_configure_raid.py
> +
Sure, are you saying we have to make that machine status allocated after raid creation.

2022-02-07 11:35 UTC, yogeshmhaskule93 commented on actions/cloudbolt_plugins/maas/configure_raid/maas_configure_raid.py
> +
Change is added

2022-02-09 00:37 UTC, smallsam approved these changes

2022-02-09 00:38 UTC, merged