Fixed the MySQL on CentOS blueprint
CloudBoltSoftware/cloudbolt-forge pull request #144
Opened 2022-02-25 14:17 UTC by cb-ishu

# Development Prerequisites
- **Developer:** @cb-ishu
- **Partner:** 
- **Jira Story:** [DEV-18563](https://cloudbolt.atlassian.net/browse/DEV-18563)
- **Design Doc:** N/A

## Summary of Proposed Changes
* Fixed issues where ordering blueprint for MySQL on CentOS.
#### Current status
* Blueprint is getting ordered successfully.
#### NOTES
* Uncomment lines 19-23 if space issues exist.
* Attached blueprint zip with proposed changes such as regex, and description for database_root_password parameter on the order form.
[mysql_on_centos (1).zip](https://github.com/CloudBoltSoftware/cloudbolt-forge/files/8141686/mysql_on_centos.1.zip)

2022-03-01 06:53 UTC, yogeshmhaskule93 requested changes

2022-03-01 06:53 UTC, yogeshmhaskule93 commented on blueprints/vmware/mysql/install_mysql_on_centos.sh
> +# dd if=/dev/zero of=/swapfile bs=1M count=1024
@cb-ishu  Can you remove commented code, if not required.

2022-03-01 06:53 UTC, yogeshmhaskule93 commented on blueprints/vmware/mysql/install_mysql_on_centos.sh
> +echo '
Is this statement required (Or it would have meaningful log message)

2022-03-01 07:11 UTC, cb-ishu commented on blueprints/vmware/mysql/install_mysql_on_centos.sh
> +# dd if=/dev/zero of=/swapfile bs=1M count=1024
@yogeshmhaskule93 I can surely remove these lines, but these are important if the testing is to be done on smaller instances. These lines of code aren't required if the instances will always have sufficient memory. Let me know if I should remove these.

2022-03-01 07:14 UTC, cb-ishu commented on blueprints/vmware/mysql/install_mysql_on_centos.sh
> +echo '
@yogeshmhaskule93 this statement is not required, they identify the steps of execution but are only required for tracking the progress of the script. I will remove these echo statements.

2022-03-01 07:31 UTC, cb-ishu commented on blueprints/vmware/mysql/install_mysql_on_centos.sh
> +echo '
Updated the script, please check.

2022-03-01 07:33 UTC, yogeshmhaskule93 approved these changes
:+1:

2022-04-27 04:59 UTC, yogeshmhaskule93 commented
Closing pull request without merge as newer changes approved and tested in a new PR.

2022-04-27 04:59 UTC, closed without merging