Template for creation of Child accounts using Cloudformation Stack Set
CloudBoltSoftware/cloudbolt-forge pull request #163
Opened 2022-11-11 08:19 UTC by abudruk

# Development Prerequisites
- **Developer:** @abudruk 
- **Partner:** @MISSING_NAME
- **Jira Story:** [XXX-22896](https://cloudbolt.atlassian.net/browse/ENG-22896)
- **Design Doc:** [Design Doc](DESIGN_DOC_URL)

## Summary of Proposed Changes
* ...

2022-11-11 11:08 UTC, yogeshmhaskule93 requested changes

2022-11-11 11:09 UTC, abudruk commented on internal/cloudformation_templates/CloudboltStackSetChildRoles.json
> +                                            "arn:aws:iam::235609055117:root"
@yogeshmhaskule93 will check it

2022-11-14 07:22 UTC, abudruk commented on internal/cloudformation_templates/CloudboltStackSetChildRoles.json
> +                                            "arn:aws:iam::235609055117:root"
@yogeshmhaskule93  Done with the changed , Kindly review the same

2022-11-14 10:15 UTC, yogeshmhaskule93 approved these changes
:+1:

2022-11-14 10:15 UTC, merged