[DEV-19412] GCP BigTable Blueprint
CloudBoltSoftware/cloudbolt-forge pull request #93
Opened 2021-07-24 20:01 UTC by RobFCloudbolt

- modified the existing GCE blueprint, now only for GCP
- location (zone) hard-coded in this commit
- changes to delete and sync also required before merging

# Development Prerequisites
- **Developer:** @RobFCloudbolt 
- **Jira Story:** [DEV-19412](https://cloudbolt.atlassian.net/browse/DEV-19412)
- **Design Doc:** [Design Doc](DESIGN_DOC_URL)

## Summary of Proposed Changes
- reusing existing GCE BigTable blueprint for GCP
- uses Google's discovery APIs ("bigtableadmin", specifically)

2021-07-25 19:11 UTC, RobFCloudbolt commented on blueprints/google_bigtable/create.py
> +    table_create_body = {"instanceId": instance_id, "instance": {"displayName": instance_id, "type": instance_type, "labels": {"createdby": "cmp"}}, "clusters": { cluster_id: {"location": location_st
the "labels" element is required; instead of passing an empty {}, I added a label to identify the DB as being created by CMP

2021-07-25 21:52 UTC, rwattscb commented on blueprints/google_bigtable/sync.py
> +            set_progress("Connection to GCE established")
Should this still say `GCE` ?

2021-07-25 22:14 UTC, RobFCloudbolt commented on blueprints/google_bigtable/sync.py
> +            set_progress("Connection to GCE established")
oops no

2021-07-26 06:24 UTC, orvisevans requested changes
I have no comments on the cit test as I don't yet know how that's supposed to work or what updates might be required. I left a couple of smallish comments, but overall this looks good otherwise!

2021-07-26 06:24 UTC, orvisevans commented on blueprints/google_bigtable/create.py
>      instance_id = '{{ db_identifier }}'
The [Content Guidelines](https://cloudbolt.atlassian.net/wiki/spaces/ENG/pages/209486096/Contributing+to+the+Content+Library#Content-Guidelines) suggest putting templated variables at the top of the file under the imports as ALL_CAPS constants.

2021-07-26 06:24 UTC, orvisevans commented on blueprints/google_bigtable/sync.py
> +            wrapper = create_bigtable_api_wrapper(handler)
I'd catch a case here where `handler.gcp_api_credentials` isn't defined, or else some other reason the wrapper fails to build, then skip that handler. Such a thing got me where a Resource Handler that wasn't finished with setup was blocking the sync script for all.

2021-07-26 16:19 UTC, orvisevans requested changes
json.loads(credentials) will error if there are no credentials. I'd check for that and return None in `create_bigtable_api_wrapper`

2021-07-26 19:01 UTC, orvisevans approved these changes

2021-08-03 14:50 UTC, merged